# playbook version fill automatically
playbook_version: 3.10.3
branch: master
# system users
_uid: root
_gid: root
# ########## emitting configuration ##########
customs: "{{_customs|default({})}}"
_local_config: "{{ (ansible_local.config|default({})).general|default({}) }}"
_tag: "{{ (branch == 'master')|ternary('latest', branch) }}"
_email: "{{ email|default(_local_config.email|default('hello@example.com'))}}"
_frontend_port: "3000"
_backend_port: "8000"
_backend_debug: 1
# need to generate through setup
_backend_secret_key: "b#5wk1l%3yf(3mab)qkp4^6x$(+&y1hri#c@7scl#k*j%skfj#"
_celery_broker: "redis://redis:6379/0"
# ########## Features ##########
setup_server: yes
# ########## Domains ##########
_domain: "{{_local_config.domain|default(ansible_host)}}"
# ########## dirs ##########
bootstrap_dir: '/srv/aviatx/bootstrap'
home_dir: '/srv/aviatx/platform'
backend_dir: '{{home_dir}}/backend'
frontend_dir: '{{home_dir}}/frontend'
envs_dir: '{{home_dir}}/envs'
media_dir: '{{home_dir}}/media'
fake_db_dir: '{{home_dir}}/db'
create_dirs:
  - ["{{ backend_dir }}", "{{ media_dir }}", "{{ fake_db_dir }}", "{{ frontend_dir }}", "{{ envs_dir }}", ]
# ########## ssh key ##########
_ssh_key: '/srv/aviatx/ssh/aviatx_rsa'
# ########## repos ##########
_git_organization: git@github.com:andrewromm
repos:
  frontend: "{{_git_organization}}/mtx_truc_front_v2.git"
  backend: "{{_git_organization}}/mtx_trac_backend.git"
# ########## ssl ##########
_letsencrypt_test: "true"
# ########## postgress ##########
_pg: 0
_pg_db: aviatx
_pg_user: "{{_local_config.domain|default('user')}}"
_pg_password: "{{_local_config.domain|default('password')}}"