version: '3'

services:
  django:
    container_name: backend
    build:
      context: ./backend/
      dockerfile: Dockerfile.prod
    command: sh -c "python manage.py collectstatic --noinput && gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
    restart: always
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
      - ./db.sqlite3:/home/app/web/db.sqlite3
    expose:
      - 8000
    env_file:
      - ./.env.django.prod

volumes:
  static_volume:
  media_volume:
    external: true
  # certs:
  # html:
  # vhost:
  # acme:
