---
- name: Installing platform
  hosts: aviatx
  become: yes
  tasks:

    - debug:
        msg: 
          domain: "{{_domain}}"
      tags: ["full"]
      # tags: ["never"]

    #### ##### ##### ##### #####    Check is python 3    ##### ##### ##### ##### ##### 

    - name: Checking python version is 3
      assert:
        that: 
          - "ansible_python_interpreter == '/usr/bin/python3'"
        msg: "Required python 3. Details: https://docs.ansible.com/ansible/latest/reference_appendices/python_3_support.html"
      tags: ["always"]

    - name: Build and set permissions for required dirs
      block:
      - name: Creating directories
        command: "mkdir -p {{ block_dirs }}"
        args:
          warn: False

      - name: Setting permissions
        command: "chown {{_uid}}:{{_gid}} {{ block_dirs }}"
        args:
          warn: False
      vars:
        block_dirs: "{{ create_dirs|flatten|join(' ') }}"
      tags: ["never", "full", "platform", "dirs"]
    
    ##### ##### ##### ##### #####    Backend    ##### ##### ##### ##### ##### 

    - name: Cloning Backend
      git:
        repo: '{{repos.backend}}'
        version: main
        clone: yes
        force: yes
        # accept_hostkey: no
        key_file: '{{_ssh_key}}'
        dest: '{{backend_dir}}'
        update: yes
      become_user: "{{_uid}}"
      tags: ['backend', 'platform', 'ppart', 'band', 'static', 'full']

    ##### ##### ##### ##### #####    Frontend    ##### ##### ##### ##### ##### 

    - name: Cloning Frontend
      git:
        repo: '{{repos.frontend}}'
        version: main
        clone: yes
        force: yes
        # accept_hostkey: no
        key_file: '{{_ssh_key}}'
        dest: '{{frontend_dir}}'
        update: yes
      become_user: "{{_uid}}"
      tags: ['backend', 'platform', 'ppart', 'band', 'static', 'full']

    ##### ##### ##### ##### #####    Docker    ##### ##### ##### ##### ##### 

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      tags: ['never', 'system', 'docker', 'full']

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
      tags: ['never', 'system', 'docker', 'full']

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true
      tags: ['never', 'system', 'docker', 'full']

    - name: Install Docker Module for Python
      pip:
        name: docker
      tags: ['never', 'system', 'docker', 'full']

    ##### ##### ##### ##### #####    Setting envs    ##### ##### ##### ##### ##### 

    - name: Set backend env variables
      template:
        src: "templates/env_django.yml.j2"
        dest: "{{envs_dir}}/.env.django.prod"
      tags: ['never', 'system', 'docker', 'full']

    - name: Set frontend env variables  
      template:
        src: "templates/env_nuxtjs.yml.j2"
        dest: "{{envs_dir}}/.env.nuxtjs.prod"
      tags: ['never', 'system', 'docker', 'full']

    - name: Set nginx proxy env variables
      template:
        src: "templates/env_proxy.yml.j2"
        dest: "{{envs_dir}}/.env.proxy.prod"
      tags: ['never', 'system', 'docker', 'full']

    ##### ##### ##### ##### #####    Docker compose    ##### ##### ##### ##### ##### 

    - name: Tear down existing services
      community.docker.docker_compose:
        project_src: "{{bootstrap_dir}}"
        state: absent
