---
- name: Installing PostgreSQL
  hosts: aviatx
  become: yes

  vars:
    postgresql_version: 12
    postgresql_backup_local_dir: "{{ pg_db_dir }}"
    postgresql_backup_dir: "{{ pg_db_dir }}"
  roles:
    - gal.postgresql
