---
  tasks:
    - name: "Find out if PostgreSQL is initialized"
      ansible.builtin.stat:
        path: "/var/lib/pgsql/data/pg_hba.conf"
      register: postgres_data
      tags: ["full"]

    - name: "Initialize PostgreSQL"
      shell: "postgresql-setup initdb"
      when: not postgres_data.stat.exists
      tags: ["full"]
 
    - name: "Start and enable services"
      service: "name={{ item }} state=started enabled=yes"
      with_items:
        - postgresql
      tags: ["full"]

    - name: "Create app database"
      postgresql_db:
        state: present
        name: "{{ _pg_db }}"
      become: yes
      become_user: postgres
      tags: ["full"]

    - name: "Create db user"
      postgresql_user:
        state: present
        name: "{{ _pg_user }}"
        password: "{{ _pg_password }}"
      become: yes
      become_user: postgres
      tags: ["full"]

    - name: "Grant db user access to app db"
      postgresql_privs:
        type: database
        database: "{{ _pg_db }}"
        roles: "{{ _pg_user }}"
        grant_option: no
        privs: all
      become: yes
      become_user: postgres
      tags: ["full"]

    - name: "Allow md5 connection for the db user"
      postgresql_pg_hba:
        dest: "~/data/pg_hba.conf"
        contype: host
        databases: all
        method: md5
        users: "{{ _pg_user }}"
        create: true
      become: yes
      become_user: postgres
      notify: restart postgres
      tags: ["full"]

  handlers:
    - name: restart postgres
      service: name=postgresql state=restarted
